on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Artifacts 
        uses: actions/download-artifact@v3

      - name: List Files
        run: ls -R
     
       

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: python-program

      - name: Run Python Program
        run: ./sum_integers.py
              
         
