on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
     
      - name: upload Artifacts 
        uses: actions/upload-artifact@v3
        with:
          path: " "
     
       

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      
       - name: Download Build Artifact
         uses: actions/download-artifact@v3
       - name: List Files
         run: ls -R
        
         

       - name: Run Python Program
       
         run: |
        
          python sum_integers.py
              
         
